ci: update test.yml (#1071)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,11 +32,14 @@ on:
   workflow_dispatch:
 
 permissions:
-  pull-requests: write
+  contents: read
 
 jobs:
   test:
     runs-on: ubuntu-latest
+    outputs:
+      is_success: ${{ steps.test.outputs.is_success }}
+      test_log: ${{ steps.test.outputs.test_log }}
     services:
       postgres:
         image: postgres
@@ -63,97 +66,94 @@ jobs:
         run: bun i
 
       - name: 🧪 Test app
+        id: test
         env:
           DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
         run: |
-          bun test:app &> >(tee -p test.log) || echo STATUS=$? >> $GITHUB_ENV
+          bun test:app &> >(tee -p test.log) || STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "is_success=false" >> $GITHUB_OUTPUT
+          else
+            echo "is_success=true" >> $GITHUB_OUTPUT
+          fi
+          UUID=$(uuidgen)
           {
-            echo 'RESULT<<EOF'
+            echo "test_log<<EOF_$UUID"
             cat test.log
-            echo EOF
-          } >> $GITHUB_ENV
+            echo "EOF_$UUID"
+          } >> $GITHUB_OUTPUT
 
-      - name: 💬 Create test comment
-        if: github.event_name == 'pull_request' && env.STATUS == 1
+      - name: 💔 Fail if test failed
+        if: steps.test.outputs.is_success == 'false'
+        run: exit 1
+
+  create_comment:
+    runs-on: ubuntu-latest
+    needs: test
+    outputs:
+      comment: ${{ env.COMMENT }}
+      title: ${{ steps.title.outputs.title }}
+    if: always() && github.event_name == 'pull_request'
+
+    steps:
+      - name: ❌ Create test failed comment
+        if: needs.test.outputs.is_success == 'false'
         env:
           ACTOR: ${{ github.actor }}
           REPO: ${{ github.repository }}
           RUN_ID: ${{ github.run_id }}
           SHA: ${{ github.event.pull_request.head.sha }}
-          WORKFLOW_REF: ${{ github.workflow_ref }}
+          TEST_LOG: ${{ needs.test.outputs.test_log }}
         run: |
+          UUID=$(uuidgen)
           {
-            echo 'TEST_COMMENT<<EOF'
-            echo '# ❌Test Failed'
+            echo "COMMENT<<EOF_$UUID"
+            echo "# ❌ Test Failed"
             echo "@$ACTOR, your commit $SHA failed the test."
-            echo '<details>'
-            echo '<summary><strong>Show Test Log</strong></summary>'
-            echo ''
+            echo ""
+            echo "<details>"
+            echo "<summary><strong>Test Log</strong></summary>"
+            echo ""
             echo "\`\`\`shell"
-            echo "$RESULT"
+            echo "$TEST_LOG"
             echo "\`\`\`"
-            echo ''
-            echo '</details>'
-            echo ''
+            echo ""
+            echo "</details>"
+            echo ""
             echo "👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)"
-            echo "<!-- generated-comment [Test]($WORKFLOW_REF) -->"
-            echo 'EOF'
+            echo "<!-- generated-comment [Test](https://github.com/$REPO/.github/workflows/test.yml) -->"
+            echo "EOF_$UUID"
           } >> $GITHUB_ENV
 
-      - name: ❌ Add a test comment
-        if: github.event_name == 'pull_request' && env.STATUS == 1
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const testComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌Test Failed')
-            })
-            if (testComment) {
-              github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: testComment.id,
-              })
-            }
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: process.env.TEST_COMMENT
-            })
+      - name: ✅ Create test success comment
+        if: needs.test.outputs.is_success == 'true'
+        env:
+          REPO: ${{ github.repository }}
+        run: |
+          UUID=$(uuidgen)
+          {
+            echo "COMMENT<<EOF_$UUID"
+            echo "# ✅ Test Passed"
+            echo "All tests passed successfully."
+            echo ""
+            echo "<!-- generated-comment [Test](https://github.com/$REPO/.github/workflows/test.yml) -->"
+            echo "EOF_$UUID"
+          } >> $GITHUB_ENV
 
-      - name: ✅ Add a Fixed comment
-        if: github.event_name == 'pull_request' && env.STATUS == 0
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const testComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌Test Failed')
-            })
-            const body = `# ✅Test Passed
+      - name: 🏳️ Set up comment title
+        id: title
+        run: |
+          echo "title=# ❌ Test Failed" >> $GITHUB_OUTPUT
 
-            Failed tests were fixed.
-            <!-- generated-comment [Test]($WORKFLOW_REF) -->`
-
-            if (testComment) {
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: body
-              })
-            }
-
-      - name: 💔 Fail if test failed
-        if: env.STATUS == 1
-        run: exit 1
+  add_comment:
+    needs:
+      - create_comment
+      - test
+    permissions:
+      pull-requests: write
+    if: always() && github.event_name == 'pull_request'
+    uses: ./.github/workflows/comment.yml
+    with:
+      comment: ${{ needs.create_comment.outputs.comment }}
+      is_success: ${{ needs.test.outputs.is_success == 'true' }}
+      title: ${{ needs.create_comment.outputs.title }}
